SUBROUTINE FLUXES(NDIM,TSN,TS,TA,QS,QA,PS,RG,RL,RA,RS,RSOIL,H,LEV,LEG,LE,RN,G)
 USE CONST
 USE SURF1
 IMPLICIT NONE
 INTEGER, INTENT(IN)                :: NDIM
 REAL, INTENT(IN),  DIMENSION(NDIM) :: TSN, TS, TA, QA, QS, PS, RG, RL, &
&                                      RA, RS, RSOIL
 REAL, INTENT(OUT), DIMENSION(NDIM) :: H, LEV, LEG, LE, RN, G
 REAL, DIMENSION(NDIM) :: ZRHO
 ZRHO = PS / (RD * TA*(1.+ 0.608*QA))
 H   = ZRHO*CP*(TSN - TA - GRAV*ZREF/CP)/RA
 LEV = ZRHO*LV*VEG*(QS - QA)/(RS + RA)
 LEG = ZRHO*LV*(1. - VEG)*(QS - QA)/(RSOIL + RA)
 LE  = LEV + LEG
 RN = -EMIS*STEFAN*TSN**4 + (1.-ALPHA)*RG + EMIS*RL 
 G   = RN - H - LE
END SUBROUTINE FLUXES
