MODULE FORC
INTEGER, PARAMETER     :: NFORC=24*62+1
REAL, PARAMETER        :: DT_FORC=3600.
REAL, DIMENSION(NFORC) :: RGF, RLF, PRF, TAF, UAF, VAF, PSF, QAF
INTEGER                :: NSTEP_TOT, NSTEP_DEB
END MODULE FORC
